const jwt = require("jsonwebtoken");
const { JWT_SECRET } = require("../config/keys");
const mongoose = require("mongoose");
const User = mongoose.model("User");

module.exports = (req, res, next) => {
    // authorization === "Bearer {Token generated by JWT}"
    const { authorization } = req.headers;
    if(!authorization) {
        return res.status(401).json({ Error : "You must be logged in to continue." });
    }
    const token = authorization.replace("Bearer ", "");
    jwt.verify(token, JWT_SECRET, (err, payload) => {
        if(err) {
            return res.status(401).json({ Error : "You must be logged in to continue." });
        }
        const { _id } = payload;
        User.findById(_id)
        .then((FoundUser) => {
            req.user = FoundUser;
            next();
        });
    });
}